# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  # - name: Home
  #   url: /
  #   weight: 1
  - name: About
    url: about
    weight: 100

  - name: People
    url: people
    weight: 200
  - parent: People
    name: Professor
    url: /author/이경수/
    weight: 210
  - parent: People
    name: Members
    url: people
    weight: 220

  - name: Publications
    url: publication
    weight: 300

  # - name: Projects
  #   url: project
  #   weight: 400


  # - name: Coursework
  #   url: publication
  #   weight: 500

  - name: Inform
    url: post
    weight: 600
  - parent: Inform
    name: News
    url: post
    weight: 620
  - parent: Inform
    name: Event
    url: event
    weight: 630


  - name: Contact
    url: contact
    weight: 700
